services:
  account:
    build:
      context: ./account
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    image: sumitk999/account:latest

  cart:
    build:
      context: ./cart
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
    restart: on-failure
    image: sumitk999/cart:latest

  catalog:
    build:
      context: ./catalog
      dockerfile: ./Dockerfile
    ports:
      - 8082:8080
    restart: on-failure
    image: sumitk999/catalog:latest

  order:
    build:
      context: ./order
      dockerfile: ./Dockerfile
    ports:
      - 8083:8080
    restart: on-failure
    image: sumitk999/order:latest

  gateway:
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 8084:8080
    depends_on:
      - account
      - catalog
      - order
      - cart
    restart: on-failure
    image: sumitk999/gateway:latest
    volumes:
      - ./gateway:/app
      - /app/tmp
    environment:
      GIN_MODE: "debug"



# Instead of mounting a volume, you can now use
 # docker compose watch feature in copy mode to
  # make docker copy files into the container once they are changed.